# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_install:
      - curl -LsSf https://astral.sh/uv/install.sh | sh
      - uv python install 3.11
      - source $HOME/.local/bin/env
    post_install:
      - uv sync --all-extras --group devel
    pre_build:
      - uv run make -C docs html

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

#python:
#  install:
#    - requirements: docs/requirements.txt
