#
# Configuration file for ruff
# See https://docs.astral.sh/ruff/configuration/

line-length = 88
indent-width = 4
include = [
    "pyproject.toml",
    "src/**/*.py",
    "tests/**/*.py",
    "docs/**/*.py",
]

[lint]
extend-ignore = [
    "RUF005",
    "RUF012",
    # Comment contains ambiguous `’` (RIGHT SINGLE QUOTATION MARK):
    "RUF003",
    "ISC001",
]
select = [
    "F", # pyflakes
    "E", # pycodestyle
    "I", # isort
    "N", # pep8-naming
    "UP", # pyupgrade
    "RUF", # ruff
    "B", # flake8-bugbear
    "C4", # flake8-comprehensions
    "ISC", # flake8-implicit-str-concat
    "PTH", # flake8-use-pathlib
    "SIM", # flake8-simplify
    "TID", # flake8-tidy-imports
]
# TODO: Remove ISC001 ignore when formatter updated: https://github.com/astral-sh/ruff/issues/8272


[format]
# Exclude type hint stub files from formatting.
exclude = ["*.pyi"]

# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

docstring-code-format = true
docstring-code-line-length = "dynamic"