language: python
install:
  - pip install --upgrade pip setuptools
  - pip install virtualenv
script: python setup.py test
matrix:
  include:
  - python: "2.7"
    env: TOXENV=py27

  - python: "3.4"
    env: TOXENV=py34

  - python: "3.4"
    env: TOXENV=flake8

  - python: "3.5"
    env: TOXENV=py35

  - python: "3.6"
    env: TOXENV=py36

  - python: "3.7"
    dist: xenial
    env: TOXENV=py37

  - python: "pypy"
    env: TOXENV=pypy
